FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PORT=8080
ENV DISABLE_DB=true

CMD ["gunicorn", "-b", "0.0.0.0:8080", "app:create_app()"]
