"""initial schema

Revision ID: 0a3a2d9ad1f1
Revises: 
Create Date: 2026-04-27 04:39:06.982081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a3a2d9ad1f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cinema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cinemaname', sa.String(length=128), nullable=True),
    sa.Column('region', sa.String(length=5), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('image_url', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cinema', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cinema_cinemaname'), ['cinemaname'], unique=True)

    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('banner_image', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_slug'), ['slug'], unique=True)

    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('moviename', sa.String(length=128), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('language', sa.String(length=128), nullable=True),
    sa.Column('releasedate', sa.Date(), nullable=True),
    sa.Column('poster_url', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('formats', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movie_moviename'), ['moviename'], unique=True)
        batch_op.create_index(batch_op.f('ix_movie_releasedate'), ['releasedate'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('halls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cinema_id', sa.Integer(), nullable=False),
    sa.Column('hallname', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['cinema_id'], ['cinema.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie_event',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'event_id')
    )
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hall_id', sa.Integer(), nullable=False),
    sa.Column('row_code', sa.String(length=5), nullable=True),
    sa.Column('seat_number', sa.Integer(), nullable=True),
    sa.Column('is_booked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['hall_id'], ['halls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('showtimes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('cinema_id', sa.Integer(), nullable=False),
    sa.Column('hall_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('format_type', sa.String(length=50), nullable=True),
    sa.Column('price_base', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cinema_id'], ['cinema.id'], ),
    sa.ForeignKeyConstraint(['hall_id'], ['halls.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('showtime_id', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['showtime_id'], ['showtimes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('ticket_code', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    op.drop_table('booking')
    op.drop_table('showtimes')
    op.drop_table('seats')
    op.drop_table('movie_event')
    op.drop_table('halls')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movie_releasedate'))
        batch_op.drop_index(batch_op.f('ix_movie_moviename'))

    op.drop_table('movie')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_slug'))

    op.drop_table('event')
    with op.batch_alter_table('cinema', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cinema_cinemaname'))

    op.drop_table('cinema')
    # ### end Alembic commands ###
