"""add cinema_id to showtimes

Revision ID: 34fbfc6da00b
Revises: da8d30373692
Create Date: 2026-04-24 14:52:38.859357

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '34fbfc6da00b'
down_revision = 'da8d30373692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('banner_image', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_slug'), ['slug'], unique=True)

    op.create_table('movie_event',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'event_id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('ticket_code', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_code')
    )
    op.drop_table('ticketing')
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moviename', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('formats', sa.JSON(), nullable=True))
        batch_op.alter_column('releasedate',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_movie_title'))
        batch_op.create_index(batch_op.f('ix_movie_moviename'), ['moviename'], unique=True)
        batch_op.drop_column('title')

    with op.batch_alter_table('seats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_booked', sa.Boolean(), nullable=True))

    with op.batch_alter_table('showtimes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cinema_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('format_type', sa.String(length=50), nullable=True))
        batch_op.alter_column('start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('price_base',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.create_foreign_key(None, 'cinema', ['cinema_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('showtimes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('price_base',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('format_type')
        batch_op.drop_column('end_time')
        batch_op.drop_column('cinema_id')

    with op.batch_alter_table('seats', schema=None) as batch_op:
        batch_op.drop_column('is_booked')

    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_movie_moviename'))
        batch_op.create_index(batch_op.f('ix_movie_title'), ['title'], unique=True)
        batch_op.alter_column('releasedate',
               existing_type=sa.Integer(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.drop_column('formats')
        batch_op.drop_column('moviename')

    op.create_table('ticketing',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('seat_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ticket_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], name=op.f('ticketing_booking_id_fkey')),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], name=op.f('ticketing_seat_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ticketing_pkey'))
    )
    op.drop_table('tickets')
    op.drop_table('movie_event')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_slug'))

    op.drop_table('event')
    # ### end Alembic commands ###
