"""increase language column length

Revision ID: 3562d7dd6346
Revises: 8b4bccb2f4ed
Create Date: 2026-04-25 02:51:57.786257

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3562d7dd6346'
down_revision = '8b4bccb2f4ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticketing')
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_festival', sa.Boolean(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_movie_title'))
        batch_op.create_index(batch_op.f('ix_movie_moviename'), ['moviename'], unique=True)

    with op.batch_alter_table('seats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_booked', sa.Boolean(), nullable=True))

    with op.batch_alter_table('showtimes', schema=None) as batch_op:
        batch_op.alter_column('cinema_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('price_base',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.create_foreign_key(None, 'cinema', ['cinema_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('showtimes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('price_base',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('cinema_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('seats', schema=None) as batch_op:
        batch_op.drop_column('is_booked')

    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movie_moviename'))
        batch_op.create_index(batch_op.f('ix_movie_title'), ['moviename'], unique=True)
        batch_op.drop_column('is_festival')

    op.create_table('ticketing',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('seat_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ticket_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], name=op.f('ticketing_booking_id_fkey')),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], name=op.f('ticketing_seat_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ticketing_pkey'))
    )
    # ### end Alembic commands ###
