"""add profile fields to user

Revision ID: 6540e8807d34
Revises: 0a3a2d9ad1f1
Create Date: 2026-04-27 10:19:46.850031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6540e8807d34'
down_revision = '0a3a2d9ad1f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('given_name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('surname', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('birth_date')
        batch_op.drop_column('gender')
        batch_op.drop_column('surname')
        batch_op.drop_column('given_name')

    # ### end Alembic commands ###
