"""empty message

Revision ID: 8b4bccb2f4ed
Revises: 34fbfc6da00b
Create Date: 2026-04-24 15:08:26.139456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8b4bccb2f4ed'
down_revision = '34fbfc6da00b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticketing')
    with op.batch_alter_table('cinema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=256), nullable=True))

    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moviename', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('formats', sa.JSON(), nullable=True))
        batch_op.alter_column('releasedate',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='releasedate::integer')
        batch_op.drop_index(batch_op.f('ix_movie_title'))
        batch_op.create_index(batch_op.f('ix_movie_moviename'), ['moviename'], unique=True)
        batch_op.drop_column('title')

    with op.batch_alter_table('seats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_booked', sa.Boolean(), nullable=True))

    with op.batch_alter_table('showtimes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cinema_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('format_type', sa.String(length=50), nullable=True))
        batch_op.alter_column('start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('price_base',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.create_foreign_key(None, 'cinema', ['cinema_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('showtimes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('price_base',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('format_type')
        batch_op.drop_column('end_time')
        batch_op.drop_column('cinema_id')

    with op.batch_alter_table('seats', schema=None) as batch_op:
        batch_op.drop_column('is_booked')

    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_movie_moviename'))
        batch_op.create_index(batch_op.f('ix_movie_title'), ['title'], unique=True)
        batch_op.alter_column('releasedate',
               existing_type=sa.Integer(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.drop_column('formats')
        batch_op.drop_column('moviename')

    with op.batch_alter_table('cinema', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    op.create_table('ticketing',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('seat_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ticket_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], name=op.f('ticketing_booking_id_fkey')),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], name=op.f('ticketing_seat_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ticketing_pkey'))
    )
    # ### end Alembic commands ###
