"""add user_id to gift_card, remove pin

Revision ID: 997d3d342720
Revises: 09cef9096b0d
Create Date: 2026-04-27 11:55:41.324310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997d3d342720'
down_revision = '09cef9096b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gift_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('pin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gift_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin', sa.VARCHAR(length=4), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
