"""increase day column

Revision ID: a4f2f63b592c
Revises: 3562d7dd6346
Create Date: 2026-04-25 04:04:10.987923

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a4f2f63b592c'
down_revision = '3562d7dd6346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('showtimes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day', sa.DateTime(), nullable=False))
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('showtimes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('day')

    # ### end Alembic commands ###
